/**
 * DEMO TRAVELLER PERSONAS
 *
 * These are CLEARLY FICTIONAL people, created so that the social side of the
 * product can be demonstrated on day one. Their photographs are generated
 * avatars, not photographs of real people. Every seeded account carries
 * `demo@` style addresses and is easy to delete (`npm run seed -- --clean`).
 */

export interface PersonaSeed {
  key: string
  email: string
  firstName: string
  lastInitial: string
  ageRange: string
  homeCity: string
  homeRegion: string
  headline: string
  bio: string
  languages: string[]
  countriesVisited: string[]
  travelPace: 'VERY_RELAXED' | 'RELAXED' | 'BALANCED' | 'ACTIVE' | 'PACKED'
  airports: string[]
  budgetPreferred: number
  budgetMax: number
  durationMin: number
  durationMax: number
  durationPreferred: number
  preferredMonths: number[]
  wishlist: { kind: 'COUNTRY' | 'CITY' | 'EXPERIENCE'; label: string; destinationSlug?: string }[]
  /** dimension key → 1..5. Unlisted dimensions are left unanswered. */
  prefs: Record<string, number>
  spectrums: Record<string, number>
  avatarTint: string
}

export const PERSONA_SEEDS: PersonaSeed[] = [
  {
    key: 'cameron',
    email: 'demo@voyaj.test',
    firstName: 'Cameron',
    lastInitial: 'W',
    ageRange: '35-44',
    homeCity: 'Toronto',
    homeRegion: 'ON',
    headline: 'Hiking, food and a good bottle of wine',
    bio: 'Usually looking for somewhere with a mountain in the morning and a proper dinner at night. Happy in a small group.',
    languages: ['English', 'French'],
    countriesVisited: ['US', 'MX', 'FR', 'IT', 'PT', 'ES', 'JP', 'CR'],
    travelPace: 'ACTIVE',
    airports: ['YYZ', 'YTZ'],
    // Wide enough that the demo account can explore most of the marketplace,
    // but still a genuine hard ceiling — a $7,000 safari is correctly hidden,
    // and the empty state explains exactly why.
    budgetPreferred: 280_000,
    budgetMax: 550_000,
    durationMin: 6,
    durationMax: 14,
    durationPreferred: 9,
    preferredMonths: [2, 3, 4, 9, 10, 11],
    wishlist: [
      { kind: 'COUNTRY', label: 'Japan', destinationSlug: 'japan' },
      { kind: 'COUNTRY', label: 'Chile', destinationSlug: 'chile' },
      { kind: 'EXPERIENCE', label: 'Northern lights' },
      { kind: 'EXPERIENCE', label: 'Italian wine country' },
      { kind: 'CITY', label: 'Porto', destinationSlug: 'porto' },
    ],
    prefs: {
      adventure: 5, hiking: 5, outdoors: 5, nature: 5, mountains: 5, wildlife: 4,
      food: 5, 'local-cuisine': 5, wine: 5, wineries: 4, 'fine-dining': 4, 'food-tours': 4,
      'coffee-culture': 4, 'street-food': 4,
      history: 4, 'local-culture': 5, architecture: 4, museums: 3, art: 3,
      'small-groups': 5, 'meeting-new-people': 4, 'quiet-evenings': 4,
      partying: 1, clubs: 1, nightlife: 2, bars: 3, 'large-groups': 2,
      'boutique-hotels': 4, 'luxury-hotels': 3, hostels: 2, 'camping-stays': 3,
      'direct-flights': 4, 'private-rooms': 4,
      relaxation: 3, beaches: 3, luxury: 3, 'budget-travel': 2, resorts: 1, 'all-inclusive': 1,
      cities: 4, countryside: 4, 'slow-travel': 4, 'road-trips': 4,
      photography: 4, kayaking: 3, skiing: 3, yoga: 2, golf: 2, spa: 3, wellness: 3,
      'guided-tours': 3, 'independent-travel': 4, cruises: 2,
    },
    spectrums: {
      'spectrum-pace': 62, 'spectrum-rhythm': 30, 'spectrum-planning': 45,
      'spectrum-guidance': 40, 'spectrum-immersion': 25, 'spectrum-comfort': 55,
      'spectrum-familiarity': 65, 'spectrum-sociability': 55, 'spectrum-spend': 60,
    },
    avatarTint: '#1F5C6B',
  },
  {
    key: 'sarah',
    email: 'demo.sarah@voyaj.test',
    firstName: 'Sarah',
    lastInitial: 'K',
    ageRange: '25-34',
    homeCity: 'Toronto',
    homeRegion: 'ON',
    headline: 'Trail runner who plans trips around dinner',
    bio: 'Up early, out late, somehow both. Looking for people who will do a 6am hike and still want a proper meal after.',
    languages: ['English'],
    countriesVisited: ['US', 'IS', 'PE', 'PT', 'TH'],
    travelPace: 'PACKED',
    airports: ['YYZ', 'YHM'],
    budgetPreferred: 210_000,
    budgetMax: 270_000,
    durationMin: 5,
    durationMax: 12,
    durationPreferred: 8,
    preferredMonths: [3, 4, 5, 9, 10],
    wishlist: [
      { kind: 'COUNTRY', label: 'Japan', destinationSlug: 'japan' },
      { kind: 'COUNTRY', label: 'Chile', destinationSlug: 'chile' },
      { kind: 'EXPERIENCE', label: 'Patagonia trek' },
    ],
    prefs: {
      adventure: 5, hiking: 5, outdoors: 5, nature: 5, mountains: 5, running: 5,
      fitness: 4, camping: 4, 'extreme-sports': 4, kayaking: 4, photography: 4,
      food: 5, 'local-cuisine': 5, 'street-food': 5, wine: 4, breweries: 4,
      'meeting-new-people': 5, 'small-groups': 5, 'social-hostels': 4, hostels: 4,
      nightlife: 3, bars: 4, partying: 2, clubs: 2,
      'budget-travel': 4, luxury: 2, 'luxury-hotels': 2, resorts: 1, 'all-inclusive': 1,
      'local-culture': 4, history: 3, museums: 2, cities: 4,
      relaxation: 2, beaches: 3, spa: 2, yoga: 3, wellness: 3,
      'independent-travel': 5, 'guided-tours': 2, 'slow-travel': 2, 'fast-paced-travel': 5,
      'road-trips': 4, cruises: 1, golf: 1, skiing: 4,
    },
    spectrums: {
      'spectrum-pace': 85, 'spectrum-rhythm': 55, 'spectrum-planning': 60,
      'spectrum-guidance': 15, 'spectrum-immersion': 15, 'spectrum-comfort': 78,
      'spectrum-familiarity': 75, 'spectrum-sociability': 70, 'spectrum-spend': 35,
    },
    avatarTint: '#C85A3C',
  },
  {
    key: 'priya',
    email: 'demo.priya@voyaj.test',
    firstName: 'Priya',
    lastInitial: 'R',
    ageRange: '25-34',
    homeCity: 'Vancouver',
    homeRegion: 'BC',
    headline: 'Museums, markets and the long way round',
    bio: 'I will happily spend a whole day in one neighbourhood. Always after the food that locals actually eat.',
    languages: ['English', 'Hindi', 'Spanish'],
    countriesVisited: ['JP', 'VN', 'IT', 'ES', 'MA', 'MX', 'PE'],
    travelPace: 'BALANCED',
    airports: ['YVR', 'YYJ'],
    budgetPreferred: 220_000,
    budgetMax: 290_000,
    durationMin: 7,
    durationMax: 16,
    durationPreferred: 11,
    preferredMonths: [4, 5, 9, 10, 11],
    wishlist: [
      { kind: 'COUNTRY', label: 'Japan', destinationSlug: 'japan' },
      { kind: 'CITY', label: 'Oaxaca', destinationSlug: 'oaxaca' },
      { kind: 'EXPERIENCE', label: 'Cooking school in Italy' },
    ],
    prefs: {
      'local-culture': 5, history: 5, museums: 5, art: 5, architecture: 5,
      'unesco-sites': 4, archaeology: 4, 'language-immersion': 4, theatre: 4,
      food: 5, 'local-cuisine': 5, 'street-food': 5, 'cooking-classes': 5,
      'food-tours': 5, 'night-markets': 5, 'coffee-culture': 5, wine: 4,
      cities: 5, 'slow-travel': 5, 'independent-travel': 4, photography: 4,
      'boutique-hotels': 4, apartments: 4, 'unique-stays': 4,
      hiking: 3, outdoors: 3, adventure: 3, nature: 3,
      partying: 1, clubs: 1, nightlife: 3, 'large-groups': 2,
      resorts: 1, 'all-inclusive': 1, cruises: 1, golf: 1, skiing: 2,
      'small-groups': 4, 'meeting-new-people': 4, 'local-interactions': 5,
      luxury: 3, 'budget-travel': 3, beaches: 3, relaxation: 3,
    },
    spectrums: {
      'spectrum-pace': 45, 'spectrum-rhythm': 45, 'spectrum-planning': 35,
      'spectrum-guidance': 25, 'spectrum-immersion': 10, 'spectrum-comfort': 40,
      'spectrum-familiarity': 80, 'spectrum-sociability': 50, 'spectrum-spend': 50,
    },
    avatarTint: '#4A6B4F',
  },
  {
    key: 'marc',
    email: 'demo.marc@voyaj.test',
    firstName: 'Marc',
    lastInitial: 'T',
    ageRange: '35-44',
    homeCity: 'Montréal',
    homeRegion: 'QC',
    headline: 'Wine first, itinerary second',
    bio: 'Give me a vineyard, a long lunch and no particular plan. I travel slowly and I eat well.',
    languages: ['French', 'English'],
    countriesVisited: ['FR', 'IT', 'ES', 'PT', 'AR', 'ZA'],
    travelPace: 'RELAXED',
    airports: ['YUL', 'YQB'],
    budgetPreferred: 320_000,
    budgetMax: 400_000,
    durationMin: 7,
    durationMax: 14,
    durationPreferred: 9,
    preferredMonths: [5, 6, 9, 10],
    wishlist: [
      { kind: 'COUNTRY', label: 'South Africa', destinationSlug: 'south-africa' },
      { kind: 'EXPERIENCE', label: 'Harvest season in Burgundy' },
    ],
    prefs: {
      wine: 5, wineries: 5, food: 5, 'fine-dining': 5, 'local-cuisine': 5,
      'cooking-classes': 4, breweries: 3, cocktails: 4, 'coffee-culture': 4,
      countryside: 5, 'slow-travel': 5, 'boutique-hotels': 5, 'luxury-hotels': 4,
      luxury: 4, 'comfortable-transport': 4, 'direct-flights': 4, 'private-rooms': 5,
      history: 4, architecture: 4, art: 4, museums: 3, 'local-culture': 4,
      hiking: 2, adventure: 2, 'extreme-sports': 1, camping: 1, hostels: 1,
      'backpacking': 1, 'budget-travel': 1,
      partying: 1, clubs: 1, nightlife: 2, 'large-groups': 1, 'social-hostels': 1,
      'quiet-evenings': 5, 'couples-travel': 4, 'small-groups': 4,
      beaches: 3, relaxation: 4, spa: 4, wellness: 3, golf: 3,
      cruises: 3, 'guided-tours': 3, 'road-trips': 4,
    },
    spectrums: {
      'spectrum-pace': 22, 'spectrum-rhythm': 55, 'spectrum-planning': 40,
      'spectrum-guidance': 45, 'spectrum-immersion': 35, 'spectrum-comfort': 20,
      'spectrum-familiarity': 40, 'spectrum-sociability': 35, 'spectrum-spend': 78,
    },
    avatarTint: '#C89B3C',
  },
  {
    key: 'jordan',
    email: 'demo.jordan@voyaj.test',
    firstName: 'Jordan',
    lastInitial: 'M',
    ageRange: '25-34',
    homeCity: 'Toronto',
    homeRegion: 'ON',
    headline: 'Beaches, music and absolutely no hiking',
    bio: 'A holiday is for resting. Find me near water with something cold and a good playlist.',
    languages: ['English'],
    countriesVisited: ['CU', 'DO', 'MX', 'JM', 'US'],
    travelPace: 'VERY_RELAXED',
    airports: ['YYZ'],
    budgetPreferred: 170_000,
    budgetMax: 220_000,
    durationMin: 5,
    durationMax: 10,
    durationPreferred: 7,
    preferredMonths: [1, 2, 3, 12],
    wishlist: [
      { kind: 'COUNTRY', label: 'Jamaica', destinationSlug: 'jamaica' },
      { kind: 'EXPERIENCE', label: 'A music festival abroad' },
    ],
    prefs: {
      beaches: 5, relaxation: 5, swimming: 5, resorts: 5, 'all-inclusive': 5,
      'resort-stays': 5, spa: 4, cocktails: 5, bars: 5, nightlife: 5,
      music: 5, 'live-entertainment': 4, festivals: 4, partying: 4, clubs: 4,
      'large-groups': 4, 'meeting-new-people': 4, 'couples-travel': 3,
      hiking: 1, mountains: 1, camping: 1, outdoors: 2, adventure: 2,
      'extreme-sports': 1, museums: 2, history: 2, archaeology: 1,
      'fine-dining': 3, food: 4, 'street-food': 4,
      luxury: 4, 'luxury-hotels': 4, 'budget-travel': 2, hostels: 2,
      'guided-tours': 2, 'organised-activities': 4, 'slow-travel': 4,
      skiing: 1, golf: 2, yoga: 2, cruises: 4,
    },
    spectrums: {
      'spectrum-pace': 15, 'spectrum-rhythm': 85, 'spectrum-planning': 30,
      'spectrum-guidance': 65, 'spectrum-immersion': 80, 'spectrum-comfort': 12,
      'spectrum-familiarity': 25, 'spectrum-sociability': 85, 'spectrum-spend': 62,
    },
    avatarTint: '#B23A54',
  },
  {
    key: 'amelia',
    email: 'demo.amelia@voyaj.test',
    firstName: 'Amelia',
    lastInitial: 'O',
    ageRange: '18-24',
    homeCity: 'Calgary',
    homeRegion: 'AB',
    headline: 'Hostels, ski hills and cheap flights',
    bio: 'Travelling on a student budget and making it work. Always up for a group trip.',
    languages: ['English'],
    countriesVisited: ['US', 'TH', 'VN'],
    travelPace: 'ACTIVE',
    airports: ['YYC', 'YEG'],
    budgetPreferred: 120_000,
    budgetMax: 160_000,
    durationMin: 7,
    durationMax: 21,
    durationPreferred: 14,
    preferredMonths: [1, 2, 5, 6, 7, 8],
    wishlist: [
      { kind: 'COUNTRY', label: 'Thailand', destinationSlug: 'thailand' },
      { kind: 'COUNTRY', label: 'Indonesia', destinationSlug: 'indonesia' },
      { kind: 'EXPERIENCE', label: 'Learn to scuba dive' },
    ],
    prefs: {
      'budget-travel': 5, hostels: 5, 'social-hostels': 5, backpacking: 5,
      'meeting-new-people': 5, 'large-groups': 4, 'small-groups': 4,
      partying: 4, nightlife: 5, bars: 5, clubs: 4, 'street-food': 5,
      'night-markets': 5, beaches: 5, swimming: 5, surfing: 4, 'scuba-diving': 4,
      snorkelling: 4, skiing: 5, snowboarding: 5, mountains: 5, hiking: 4,
      adventure: 5, 'extreme-sports': 4, outdoors: 4, camping: 4,
      luxury: 1, 'luxury-hotels': 1, 'fine-dining': 1, resorts: 2, 'all-inclusive': 2,
      'premium-flights': 1, 'private-rooms': 2,
      food: 4, 'local-culture': 4, history: 3, museums: 2,
      'independent-travel': 4, 'spontaneous-travel': 5, 'slow-travel': 3,
      golf: 1, cruises: 1, spa: 2, wellness: 2,
    },
    spectrums: {
      'spectrum-pace': 70, 'spectrum-rhythm': 80, 'spectrum-planning': 80,
      'spectrum-guidance': 25, 'spectrum-immersion': 25, 'spectrum-comfort': 85,
      'spectrum-familiarity': 78, 'spectrum-sociability': 90, 'spectrum-spend': 12,
    },
    avatarTint: '#4D8895',
  },
  {
    key: 'daniel',
    email: 'demo.daniel@voyaj.test',
    firstName: 'Daniel',
    lastInitial: 'B',
    ageRange: '45-54',
    homeCity: 'Ottawa',
    homeRegion: 'ON',
    headline: 'Wildlife, cameras and early starts',
    bio: 'Twenty years of safari and still not bored. Happy to be up at five if there is something worth photographing.',
    languages: ['English', 'French'],
    countriesVisited: ['TZ', 'KE', 'ZA', 'BW', 'CR', 'EC'],
    travelPace: 'BALANCED',
    airports: ['YOW', 'YUL', 'YYZ'],
    budgetPreferred: 550_000,
    budgetMax: 750_000,
    durationMin: 8,
    durationMax: 18,
    durationPreferred: 12,
    preferredMonths: [6, 7, 8, 9],
    wishlist: [
      { kind: 'COUNTRY', label: 'Tanzania', destinationSlug: 'tanzania' },
      { kind: 'EXPERIENCE', label: 'Safari migration crossing' },
    ],
    prefs: {
      wildlife: 5, photography: 5, nature: 5, outdoors: 5, 'guided-tours': 5,
      'small-groups': 5, glamping: 4, 'unique-stays': 4, camping: 3,
      'quiet-evenings': 5, 'indigenous-culture': 4, 'local-culture': 4,
      luxury: 4, 'luxury-hotels': 3, 'comfortable-transport': 4, 'direct-flights': 4,
      hiking: 4, mountains: 3, adventure: 4,
      partying: 1, clubs: 1, nightlife: 1, bars: 2, 'large-groups': 2,
      beaches: 2, resorts: 1, 'all-inclusive': 1, cruises: 3,
      food: 3, wine: 3, 'fine-dining': 3, museums: 3, history: 4,
      skiing: 2, golf: 2, yoga: 1, spa: 2,
    },
    spectrums: {
      'spectrum-pace': 50, 'spectrum-rhythm': 8, 'spectrum-planning': 20,
      'spectrum-guidance': 85, 'spectrum-immersion': 30, 'spectrum-comfort': 45,
      'spectrum-familiarity': 82, 'spectrum-sociability': 30, 'spectrum-spend': 72,
    },
    avatarTint: '#333B45',
  },
  {
    key: 'nina',
    email: 'demo.nina@voyaj.test',
    firstName: 'Nina',
    lastInitial: 'S',
    ageRange: '35-44',
    homeCity: 'Halifax',
    homeRegion: 'NS',
    headline: 'Yoga, quiet beaches, early nights',
    bio: 'Travelling to slow down. Looking for warm water, good light and nobody playing music at me.',
    languages: ['English'],
    countriesVisited: ['PT', 'ID', 'CR', 'MX'],
    travelPace: 'VERY_RELAXED',
    airports: ['YHZ', 'YYZ'],
    budgetPreferred: 230_000,
    budgetMax: 300_000,
    durationMin: 7,
    durationMax: 14,
    durationPreferred: 10,
    preferredMonths: [1, 2, 3, 4, 11],
    wishlist: [
      { kind: 'COUNTRY', label: 'Indonesia', destinationSlug: 'indonesia' },
      { kind: 'EXPERIENCE', label: 'A proper yoga retreat' },
    ],
    prefs: {
      yoga: 5, wellness: 5, spa: 5, relaxation: 5, 'quiet-evenings': 5,
      'slow-travel': 5, beaches: 5, swimming: 5, nature: 4, 'boutique-hotels': 4,
      'unique-stays': 4, 'local-cuisine': 4, food: 4, 'coffee-culture': 4,
      'religion-spirituality': 3, 'local-culture': 4, photography: 3,
      partying: 1, clubs: 1, nightlife: 1, bars: 2, 'large-groups': 1,
      'social-hostels': 1, hostels: 1, festivals: 2,
      hiking: 3, outdoors: 3, adventure: 2, 'extreme-sports': 1, skiing: 1,
      luxury: 4, 'luxury-hotels': 3, 'all-inclusive': 2, resorts: 3,
      'small-groups': 4, 'meeting-new-people': 3, 'couples-travel': 3,
      surfing: 3, snorkelling: 3, cruises: 2, golf: 1,
    },
    spectrums: {
      'spectrum-pace': 12, 'spectrum-rhythm': 12, 'spectrum-planning': 35,
      'spectrum-guidance': 55, 'spectrum-immersion': 35, 'spectrum-comfort': 25,
      'spectrum-familiarity': 55, 'spectrum-sociability': 25, 'spectrum-spend': 62,
    },
    avatarTint: '#A3B8A6',
  },
  {
    key: 'wes',
    email: 'demo.wes@voyaj.test',
    firstName: 'Wes',
    lastInitial: 'A',
    ageRange: '25-34',
    homeCity: 'Winnipeg',
    homeRegion: 'MB',
    headline: 'Ski season, then somewhere warm',
    bio: 'Two trips a year: one with snow, one without. Usually with a group.',
    languages: ['English'],
    countriesVisited: ['US', 'FR', 'JP', 'MX'],
    travelPace: 'ACTIVE',
    airports: ['YWG', 'YYZ'],
    budgetPreferred: 260_000,
    budgetMax: 340_000,
    durationMin: 5,
    durationMax: 12,
    durationPreferred: 8,
    preferredMonths: [1, 2, 3, 7, 8],
    wishlist: [
      { kind: 'COUNTRY', label: 'Japan', destinationSlug: 'japan' },
      { kind: 'EXPERIENCE', label: 'Niseko powder' },
    ],
    prefs: {
      skiing: 5, snowboarding: 5, mountains: 5, outdoors: 4, adventure: 4,
      'small-groups': 5, 'meeting-new-people': 4, bars: 4, nightlife: 4,
      food: 4, 'local-cuisine': 4, breweries: 4, 'street-food': 4,
      beaches: 4, swimming: 4, surfing: 3, relaxation: 4, resorts: 3,
      hiking: 4, camping: 3, fitness: 4, 'water-sports': 4,
      luxury: 3, 'luxury-hotels': 3, 'budget-travel': 3, hostels: 3,
      partying: 3, clubs: 3, museums: 2, history: 2, art: 2,
      'guided-tours': 2, 'independent-travel': 4, cruises: 1, golf: 3,
    },
    spectrums: {
      'spectrum-pace': 68, 'spectrum-rhythm': 62, 'spectrum-planning': 55,
      'spectrum-guidance': 30, 'spectrum-immersion': 45, 'spectrum-comfort': 55,
      'spectrum-familiarity': 55, 'spectrum-sociability': 72, 'spectrum-spend': 52,
    },
    avatarTint: '#7FB0BB',
  },
  {
    key: 'leah',
    email: 'demo.leah@voyaj.test',
    firstName: 'Leah',
    lastInitial: 'G',
    ageRange: '55-64',
    homeCity: 'Victoria',
    homeRegion: 'BC',
    headline: 'Rail journeys and long walks',
    bio: 'Retired and finally travelling properly. Trains over planes where I can, and I like a guide who knows the history.',
    languages: ['English', 'German'],
    countriesVisited: ['GB', 'FR', 'DE', 'CH', 'IT', 'JP', 'PT'],
    travelPace: 'RELAXED',
    airports: ['YVR', 'YYJ'],
    budgetPreferred: 380_000,
    budgetMax: 480_000,
    durationMin: 10,
    durationMax: 21,
    durationPreferred: 14,
    preferredMonths: [4, 5, 6, 9, 10],
    wishlist: [
      { kind: 'COUNTRY', label: 'Japan', destinationSlug: 'japan' },
      { kind: 'CITY', label: 'Kyoto', destinationSlug: 'kyoto' },
    ],
    prefs: {
      history: 5, museums: 5, architecture: 5, art: 5, 'local-culture': 5,
      'unesco-sites': 5, theatre: 4, music: 4, 'guided-tours': 5,
      'comfortable-transport': 5, 'slow-travel': 5, 'boutique-hotels': 4,
      'luxury-hotels': 4, 'private-rooms': 5, 'direct-flights': 4,
      food: 4, 'local-cuisine': 4, wine: 4, 'fine-dining': 4,
      hiking: 4, countryside: 4, nature: 4, outdoors: 3,
      partying: 1, clubs: 1, nightlife: 1, 'social-hostels': 1, hostels: 1,
      backpacking: 1, 'extreme-sports': 1, camping: 1,
      'quiet-evenings': 5, 'small-groups': 5, 'large-groups': 2,
      cruises: 4, beaches: 3, relaxation: 4, spa: 3, luxury: 4,
    },
    spectrums: {
      'spectrum-pace': 40, 'spectrum-rhythm': 20, 'spectrum-planning': 20,
      'spectrum-guidance': 75, 'spectrum-immersion': 40, 'spectrum-comfort': 22,
      'spectrum-familiarity': 60, 'spectrum-sociability': 35, 'spectrum-spend': 70,
    },
    avatarTint: '#833739',
  },
  {
    key: 'tomas',
    email: 'demo.tomas@voyaj.test',
    firstName: 'Tomás',
    lastInitial: 'V',
    ageRange: '35-44',
    homeCity: 'Edmonton',
    homeRegion: 'AB',
    headline: 'Road trips and national parks',
    bio: 'Give me a car, a cooler and a week. I would rather drive it than fly over it.',
    languages: ['English', 'Spanish'],
    countriesVisited: ['US', 'IS', 'NZ', 'CL'],
    travelPace: 'BALANCED',
    airports: ['YEG', 'YYC'],
    budgetPreferred: 190_000,
    budgetMax: 250_000,
    durationMin: 6,
    durationMax: 16,
    durationPreferred: 10,
    preferredMonths: [5, 6, 7, 8, 9],
    wishlist: [
      { kind: 'COUNTRY', label: 'Iceland', destinationSlug: 'iceland' },
      { kind: 'EXPERIENCE', label: 'Drive the Ring Road' },
    ],
    prefs: {
      'road-trips': 5, 'independent-travel': 5, 'spontaneous-travel': 5,
      outdoors: 5, nature: 5, mountains: 4, hiking: 4, camping: 4, wildlife: 4,
      photography: 5, 'unique-stays': 4, apartments: 4,
      'guided-tours': 1, 'structured-itineraries': 1, 'organised-activities': 2,
      cruises: 1, resorts: 1, 'all-inclusive': 1, 'large-groups': 1,
      food: 4, breweries: 4, 'local-cuisine': 4, 'coffee-culture': 4,
      luxury: 2, 'budget-travel': 4, 'quiet-evenings': 4,
      partying: 1, clubs: 1, nightlife: 2, museums: 3, history: 3,
      beaches: 3, swimming: 3, skiing: 3, golf: 1, spa: 2,
    },
    spectrums: {
      'spectrum-pace': 55, 'spectrum-rhythm': 30, 'spectrum-planning': 88,
      'spectrum-guidance': 5, 'spectrum-immersion': 20, 'spectrum-comfort': 70,
      'spectrum-familiarity': 50, 'spectrum-sociability': 30, 'spectrum-spend': 32,
    },
    avatarTint: '#4A6B4F',
  },
  {
    key: 'ify',
    email: 'demo.ify@voyaj.test',
    firstName: 'Ify',
    lastInitial: 'N',
    ageRange: '25-34',
    homeCity: 'Toronto',
    homeRegion: 'ON',
    headline: 'City breaks and gallery openings',
    bio: 'Short trips, often. I would rather do four days somewhere properly than two weeks drifting.',
    languages: ['English', 'Igbo'],
    countriesVisited: ['GB', 'FR', 'NL', 'PT', 'ES', 'MA'],
    travelPace: 'PACKED',
    airports: ['YYZ', 'YTZ'],
    budgetPreferred: 140_000,
    budgetMax: 190_000,
    durationMin: 3,
    durationMax: 7,
    durationPreferred: 4,
    preferredMonths: [3, 4, 5, 9, 10, 11],
    wishlist: [
      { kind: 'CITY', label: 'Lisbon', destinationSlug: 'lisbon' },
      { kind: 'CITY', label: 'Barcelona', destinationSlug: 'barcelona' },
    ],
    prefs: {
      cities: 5, art: 5, museums: 5, architecture: 5, 'local-culture': 4,
      history: 4, theatre: 4, music: 4, 'live-entertainment': 4, festivals: 4,
      food: 5, 'fine-dining': 4, 'coffee-culture': 5, cocktails: 4, bars: 4,
      nightlife: 4, 'boutique-hotels': 4, apartments: 4,
      'independent-travel': 5, 'fast-paced-travel': 5, 'slow-travel': 2,
      hiking: 1, camping: 1, outdoors: 2, mountains: 1, wildlife: 2,
      cruises: 1, resorts: 1, 'all-inclusive': 1, golf: 1, skiing: 1, fishing: 1,
      beaches: 3, relaxation: 2, spa: 3, luxury: 3, 'budget-travel': 3,
      'small-groups': 3, 'couples-travel': 3, partying: 3,
    },
    spectrums: {
      'spectrum-pace': 88, 'spectrum-rhythm': 70, 'spectrum-planning': 45,
      'spectrum-guidance': 15, 'spectrum-immersion': 30, 'spectrum-comfort': 20,
      'spectrum-familiarity': 45, 'spectrum-sociability': 60, 'spectrum-spend': 48,
    },
    avatarTint: '#C85A3C',
  },
]
