/**
 * DEMO DEAL CATALOGUE
 *
 * Hand-written, realistic travel products used to populate the marketplace for
 * development and the investor demonstration. Every deal created from these
 * templates is flagged `isDemoContent = true` and is labelled in the interface
 * as demonstration inventory — it must never be presented as a live offer.
 *
 * The seeder expands each template into several dated departures from
 * different Canadian gateways, which is how real tour inventory behaves.
 */

export interface DealTemplate {
  ref: string
  provider: string
  title: string
  description: string
  destinationSlug: string
  country: string
  region?: string
  city?: string
  continent: string
  arrivalIata?: string
  /** Gateways this product is genuinely sold from. */
  departures: string[]
  nights: number
  basePriceCents: number
  regularPriceCents?: number
  /** Price difference by departure gateway, in cents. */
  gatewayPremium?: Record<string, number>
  airfareIncluded: boolean | null
  accommodationIncluded: boolean | null
  mealsIncluded: boolean | null
  mealsDescription?: string
  activitiesIncluded: boolean | null
  transportIncluded: boolean | null
  guideIncluded: boolean | null
  accommodationType: string | null
  accommodationQuality: number | null
  groupSizeMin?: number
  groupSizeMax?: number
  minAge?: number
  physicalDifficulty: 'EASY' | 'MODERATE' | 'CHALLENGING' | 'STRENUOUS' | 'NOT_SPECIFIED'
  activityLevel?: number
  tripStyle: string[]
  soloFriendly?: boolean
  /** dimension key → intensity 0..1. These are SOURCE-grade facts. */
  attributes: Record<string, number>
  inclusions: string[]
  exclusions: string[]
  itinerary?: { title: string; description: string; location?: string }[]
  images: string[]
  cancellationPolicy?: string
  /** Months (1-12) this product actually runs. */
  months: number[]
  /** Deliberately incomplete records, to prove the UI handles missing data. */
  incomplete?: boolean
}

const u = (id: string) => `https://images.unsplash.com/photo-${id}?w=1400&q=72`

export const DEAL_TEMPLATES: DealTemplate[] = [
  // ─────────────────────────── ADVENTURE / HIKING ───────────────────────────
  {
    ref: 'CR-RAINFOREST-7',
    provider: 'northbound-adventures',
    title: 'Costa Rica: Rainforest, Volcanoes & Pacific Coast',
    description:
      'A seven-night small-group trip across Costa Rica, starting in the cloud forest at Monteverde before moving to Arenal for volcano hikes and hot springs, then finishing on the Pacific at Manuel Antonio. Days are active — expect three to five hours of walking on trail days — with evenings spent in locally owned lodges. Group size is capped at twelve.',
    destinationSlug: 'costa-rica',
    country: 'CR', region: 'Central Pacific', city: 'San José', continent: 'Central America',
    arrivalIata: 'SJO',
    departures: ['YYZ', 'YUL', 'YVR', 'YYC'],
    nights: 7,
    basePriceCents: 268_900,
    regularPriceCents: 329_900,
    gatewayPremium: { YVR: 22_000, YYC: 14_000, YUL: 4_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '7 breakfasts, 3 dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Eco-lodges and small hotels', accommodationQuality: 3,
    groupSizeMin: 6, groupSizeMax: 12, minAge: 18,
    physicalDifficulty: 'MODERATE', activityLevel: 4,
    tripStyle: ['adventure-tour', 'hiking-tour', 'solo-friendly'],
    soloFriendly: true,
    attributes: {
      adventure: 0.85, hiking: 0.9, outdoors: 0.9, nature: 0.95, wildlife: 0.85,
      'small-groups': 0.9, 'meeting-new-people': 0.75, beaches: 0.6, swimming: 0.55,
      luxury: 0.25, 'luxury-hotels': 0.2, nightlife: 0.15, partying: 0.1,
      food: 0.6, 'local-cuisine': 0.65, 'local-culture': 0.6, photography: 0.7,
      'guided-tours': 0.85, kayaking: 0.5, 'extreme-sports': 0.45, 'quiet-evenings': 0.6,
      'spectrum-pace': 0.65, 'spectrum-comfort': 0.7, 'spectrum-sociability': 0.65,
      'spectrum-spend': 0.35, 'spectrum-guidance': 0.8, 'spectrum-rhythm': 0.25,
    },
    inclusions: [
      'Return flights from your selected Canadian gateway',
      '7 nights in eco-lodges and small hotels',
      'All ground transport in Costa Rica',
      'English-speaking local guide throughout',
      'Monteverde cloud forest walk',
      'Arenal volcano hike and hot springs entry',
      '7 breakfasts and 3 dinners',
    ],
    exclusions: ['Travel insurance', 'Most lunches and dinners', 'Optional zip-line excursion', 'Gratuities'],
    itinerary: [
      { title: 'Arrive San José', description: 'Airport transfer and welcome dinner with your group.', location: 'San José' },
      { title: 'Monteverde cloud forest', description: 'Transfer to Monteverde. Afternoon guided walk on the suspension bridges.', location: 'Monteverde' },
      { title: 'Monteverde to Arenal', description: 'Boat crossing over Lake Arenal, then an afternoon at leisure.', location: 'La Fortuna' },
      { title: 'Arenal volcano', description: 'Morning hike across the 1968 lava flow, afternoon at the hot springs.', location: 'La Fortuna' },
      { title: 'To the Pacific coast', description: 'Long transfer day to Manuel Antonio with a stop at a crocodile bridge.', location: 'Manuel Antonio' },
      { title: 'Manuel Antonio National Park', description: 'Guided wildlife walk, then a free afternoon on the beach.', location: 'Manuel Antonio' },
      { title: 'Free day', description: 'Optional surf lesson, kayaking or a day doing nothing at all.', location: 'Manuel Antonio' },
      { title: 'Return home', description: 'Transfer to San José for your flight.', location: 'San José' },
    ],
    images: [u('1536513879909-3c7a3a7c8e2b'), u('1518182170546-07661fd94144'), u('1552465011-b4e21bf6e79a')],
    cancellationPolicy: 'Free cancellation up to 60 days before departure. 50% refund 30-59 days. No refund inside 30 days.',
    months: [1, 2, 3, 4, 11, 12],
  },
  {
    ref: 'PATAGONIA-TREK-10',
    provider: 'northbound-adventures',
    title: 'Patagonia: Torres del Paine W Trek',
    description:
      'Ten nights in Chilean Patagonia built around the classic W trek in Torres del Paine. Four consecutive trekking days of six to nine hours, staying in mountain refugios, bookended by nights in Puerto Natales. This is a genuinely demanding trip and you should be comfortable walking all day with a daypack in changeable weather.',
    destinationSlug: 'patagonia',
    country: 'CL', region: 'Magallanes', continent: 'South America',
    arrivalIata: 'SCL',
    departures: ['YYZ', 'YUL', 'YVR'],
    nights: 10,
    basePriceCents: 489_900,
    regularPriceCents: 559_900,
    gatewayPremium: { YVR: 18_000, YUL: 6_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals on trekking days',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Mountain refugios and hotels', accommodationQuality: 2,
    groupSizeMin: 4, groupSizeMax: 10, minAge: 18,
    physicalDifficulty: 'STRENUOUS', activityLevel: 5,
    tripStyle: ['hiking-tour', 'adventure-tour', 'expedition'],
    soloFriendly: true,
    attributes: {
      hiking: 1.0, adventure: 0.95, outdoors: 1.0, mountains: 1.0, nature: 0.9,
      camping: 0.6, photography: 0.75, 'small-groups': 0.85, wildlife: 0.5,
      luxury: 0.1, 'luxury-hotels': 0.05, nightlife: 0.02, partying: 0.02,
      beaches: 0.05, 'fine-dining': 0.1, 'quiet-evenings': 0.85,
      'spectrum-pace': 0.85, 'spectrum-comfort': 0.95, 'spectrum-spend': 0.4,
      'spectrum-rhythm': 0.1, 'spectrum-sociability': 0.5, 'spectrum-guidance': 0.7,
    },
    inclusions: [
      'Return flights from your selected Canadian gateway',
      'Internal flights Santiago to Punta Arenas',
      '10 nights accommodation including 4 in mountain refugios',
      'All meals on trekking days',
      'Park entry fees and catamaran crossings',
      'Certified mountain guide',
    ],
    exclusions: ['Travel insurance (mandatory)', 'Meals in Puerto Natales', 'Hiking equipment hire', 'Gratuities'],
    images: [u('1478827387698-1527781a4887'), u('1531176175280-33e81e0c2c81'), u('1483347756197-71ef80e95f73')],
    cancellationPolicy: 'Free cancellation up to 90 days. 25% refund 45-89 days. No refund inside 45 days.',
    months: [11, 12, 1, 2, 3],
  },
  {
    ref: 'DOLOMITES-HUT-7',
    provider: 'northbound-adventures',
    title: 'Italian Dolomites: Hut-to-Hut Walking',
    description:
      'Seven nights walking between mountain huts in the Alta Badia region, with luggage transferred ahead of you. Days are four to six hours on well-marked paths with significant ascent. Huts are simple but the food is excellent and the terrace views are the point.',
    destinationSlug: 'dolomites',
    country: 'IT', region: 'Trentino-Alto Adige', continent: 'Europe',
    arrivalIata: 'VCE',
    departures: ['YYZ', 'YUL'],
    nights: 7,
    basePriceCents: 342_900,
    regularPriceCents: 389_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Half board throughout',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Mountain huts (rifugi)', accommodationQuality: 3,
    groupSizeMin: 4, groupSizeMax: 14,
    physicalDifficulty: 'CHALLENGING', activityLevel: 4,
    tripStyle: ['hiking-tour', 'adventure-tour'],
    soloFriendly: true,
    attributes: {
      hiking: 0.98, mountains: 0.95, outdoors: 0.95, nature: 0.85, adventure: 0.7,
      food: 0.7, 'local-cuisine': 0.75, wine: 0.6, 'small-groups': 0.8,
      photography: 0.7, 'quiet-evenings': 0.8, luxury: 0.25, nightlife: 0.05,
      partying: 0.03, 'local-culture': 0.6, beaches: 0.02,
      'spectrum-pace': 0.7, 'spectrum-comfort': 0.75, 'spectrum-spend': 0.5,
      'spectrum-rhythm': 0.15, 'spectrum-guidance': 0.7,
    },
    inclusions: ['Return flights to Venice', '7 nights half board in mountain huts', 'Daily luggage transfer', 'Qualified mountain guide', 'Cable car passes'],
    exclusions: ['Travel insurance', 'Lunches', 'Drinks with dinner'],
    images: [u('1601999009164-bcd12ccab2d8'), u('1464822759023-fed622ff2c3b')],
    months: [6, 7, 8, 9],
  },
  {
    ref: 'BANFF-ROCKIES-5',
    provider: 'trailhead-domestic',
    title: 'Canadian Rockies: Banff, Yoho & Lake Louise',
    description:
      'Five nights based in Banff and Field with day hikes into Yoho and around Lake Louise. Land only — you arrange your own flights or drive, which keeps the price down for anyone in Alberta or BC. Hikes range from easy lakeside walks to a full day on the Plain of Six Glaciers.',
    destinationSlug: 'banff',
    country: 'CA', region: 'Alberta', city: 'Banff', continent: 'North America',
    arrivalIata: 'YYC',
    departures: ['YYC', 'YEG', 'YVR'],
    nights: 5,
    basePriceCents: 149_900,
    regularPriceCents: 179_900,
    airfareIncluded: false, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '5 breakfasts',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Mountain lodges', accommodationQuality: 3,
    groupSizeMax: 12,
    physicalDifficulty: 'MODERATE', activityLevel: 4,
    tripStyle: ['hiking-tour', 'adventure-tour', 'road-trip'],
    soloFriendly: true,
    attributes: {
      hiking: 0.95, mountains: 1.0, outdoors: 0.95, nature: 0.9, wildlife: 0.7,
      photography: 0.8, camping: 0.3, 'small-groups': 0.8, adventure: 0.7,
      luxury: 0.3, nightlife: 0.1, partying: 0.05, beaches: 0.02,
      'quiet-evenings': 0.75, 'local-culture': 0.3,
      'spectrum-pace': 0.7, 'spectrum-comfort': 0.7, 'spectrum-spend': 0.4,
      'spectrum-familiarity': 0.2, 'spectrum-rhythm': 0.2,
    },
    inclusions: ['5 nights in mountain lodges', '5 breakfasts', 'All ground transport from Calgary', 'National park passes', 'Certified hiking guide'],
    exclusions: ['Flights', 'Lunches and dinners', 'Travel insurance'],
    images: [u('1609825488888-3a766db05542'), u('1513415431242-bc9c98e6d2d1')],
    months: [6, 7, 8, 9],
  },

  // ──────────────────────────── FOOD & WINE ────────────────────────────────
  {
    ref: 'PORTUGAL-DOURO-8',
    provider: 'terra-vine-collective',
    title: 'Portugal: Lisbon, Porto & the Douro Valley',
    description:
      'Eight nights moving from Lisbon to Porto and up into the Douro, built entirely around eating and drinking well. Two vineyard days with tastings, a Lisbon market tour, a cooking class in Porto and a river cruise through the terraced valley. Walking is moderate and mostly urban.',
    destinationSlug: 'portugal',
    country: 'PT', region: 'Norte', city: 'Porto', continent: 'Europe',
    arrivalIata: 'LIS',
    departures: ['YYZ', 'YUL', 'YHZ', 'YVR'],
    nights: 8,
    basePriceCents: 314_900,
    regularPriceCents: 379_900,
    gatewayPremium: { YVR: 26_000, YHZ: -12_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '8 breakfasts, 4 dinners with wine',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Boutique hotels and a quinta', accommodationQuality: 4,
    groupSizeMin: 6, groupSizeMax: 16,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['food-wine', 'cultural', 'tour'],
    soloFriendly: true,
    attributes: {
      food: 0.98, wine: 1.0, wineries: 0.95, 'local-cuisine': 0.9, 'fine-dining': 0.75,
      'cooking-classes': 0.8, 'food-tours': 0.85, 'coffee-culture': 0.6,
      cities: 0.8, 'local-culture': 0.8, history: 0.65, architecture: 0.7,
      'boutique-hotels': 0.85, luxury: 0.6, 'slow-travel': 0.75, countryside: 0.6,
      hiking: 0.15, adventure: 0.2, partying: 0.2, nightlife: 0.4, beaches: 0.25,
      'small-groups': 0.8, 'quiet-evenings': 0.5,
      'spectrum-pace': 0.35, 'spectrum-comfort': 0.25, 'spectrum-spend': 0.65,
      'spectrum-immersion': 0.35, 'spectrum-rhythm': 0.6,
    },
    inclusions: ['Return flights', '8 nights in boutique hotels and a Douro quinta', 'Lisbon food market tour', 'Two vineyard visits with tastings', 'Porto cooking class', 'Douro river cruise', '8 breakfasts and 4 dinners with wine'],
    exclusions: ['Travel insurance', 'Lunches', 'Additional wine purchases'],
    itinerary: [
      { title: 'Arrive Lisbon', description: 'Transfer to your hotel in Chiado. Evening welcome dinner.', location: 'Lisbon' },
      { title: 'Lisbon food markets', description: 'Guided tasting tour through Mercado da Ribeira and Alfama.', location: 'Lisbon' },
      { title: 'Lisbon free day', description: 'Optional day trip to Sintra, or nothing at all.', location: 'Lisbon' },
      { title: 'Train to Porto', description: 'Morning train north. Afternoon walking tour of Ribeira.', location: 'Porto' },
      { title: 'Port houses', description: 'Vila Nova de Gaia cellars and a vertical tasting.', location: 'Porto' },
      { title: 'Cooking class', description: 'Hands-on class with a Porto chef, then dinner with what you made.', location: 'Porto' },
      { title: 'Into the Douro', description: 'Drive up the valley to a working quinta. Harvest-season visits include treading.', location: 'Douro Valley' },
      { title: 'River cruise', description: 'Morning on the river, afternoon tasting, final dinner at the quinta.', location: 'Douro Valley' },
      { title: 'Return home', description: 'Transfer to Porto airport.', location: 'Porto' },
    ],
    images: [u('1555881400-74d7acaacd8b'), u('1506377247377-2a5b3b417ebb'), u('1513735492246-483525079686')],
    cancellationPolicy: 'Free cancellation up to 45 days. 50% refund 21-44 days.',
    months: [4, 5, 6, 9, 10, 11],
  },
  {
    ref: 'TUSCANY-FOOD-7',
    provider: 'terra-vine-collective',
    title: 'Tuscany: Slow Food, Chianti & Florence',
    description:
      'Seven nights based in a restored farmhouse in Chianti with day trips to Florence, Siena and San Gimignano. Two cooking classes, three winery visits and a truffle hunt in season. Deliberately unhurried — there is a pool and most afternoons are free.',
    destinationSlug: 'tuscany',
    country: 'IT', region: 'Tuscany', city: 'Florence', continent: 'Europe',
    arrivalIata: 'FCO',
    departures: ['YYZ', 'YUL'],
    nights: 7,
    basePriceCents: 389_900,
    regularPriceCents: 449_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '7 breakfasts, 5 dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Restored farmhouse (agriturismo)', accommodationQuality: 4,
    groupSizeMax: 14,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['food-wine', 'cultural', 'tour'],
    attributes: {
      food: 1.0, wine: 0.95, wineries: 0.9, 'fine-dining': 0.7, 'cooking-classes': 0.9,
      'local-cuisine': 0.9, art: 0.75, history: 0.8, museums: 0.7, architecture: 0.8,
      countryside: 0.9, 'slow-travel': 0.9, luxury: 0.6, 'boutique-hotels': 0.6,
      relaxation: 0.7, swimming: 0.5, hiking: 0.2, adventure: 0.15,
      nightlife: 0.2, partying: 0.1, 'quiet-evenings': 0.8,
      'spectrum-pace': 0.25, 'spectrum-spend': 0.65, 'spectrum-comfort': 0.2,
      'spectrum-rhythm': 0.4,
    },
    inclusions: ['Return flights to Rome', '7 nights in a Chianti farmhouse', 'Two cooking classes', 'Three winery visits', 'Day trips to Florence and Siena', '7 breakfasts and 5 dinners'],
    exclusions: ['Travel insurance', 'Museum entry in Florence', 'Lunches'],
    images: [u('1523906834658-6e24ef2386f9'), u('1543965170-4c01a586684e')],
    months: [5, 6, 9, 10],
  },
  {
    ref: 'CAPE-WINE-9',
    provider: 'terra-vine-collective',
    title: 'South Africa: Cape Town, Winelands & Safari',
    description:
      'Nine nights combining Cape Town, the Stellenbosch winelands and three nights on a private game reserve. Two game drives a day at the reserve, wine tastings in the Cape, and time on the coast. A wide-ranging trip that suits people who cannot decide between a city, a vineyard and a safari.',
    destinationSlug: 'south-africa',
    country: 'ZA', region: 'Western Cape', city: 'Cape Town', continent: 'Africa',
    arrivalIata: 'CPT',
    departures: ['YYZ', 'YUL'],
    nights: 9,
    basePriceCents: 578_900,
    regularPriceCents: 669_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals on safari, breakfasts elsewhere',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Boutique hotels and a safari lodge', accommodationQuality: 4,
    groupSizeMax: 12,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['food-wine', 'adventure-tour', 'tour'],
    attributes: {
      wine: 0.9, wineries: 0.9, food: 0.85, 'fine-dining': 0.8, wildlife: 0.95,
      photography: 0.85, nature: 0.8, luxury: 0.75, 'luxury-hotels': 0.7,
      cities: 0.7, 'local-culture': 0.7, beaches: 0.5, adventure: 0.55,
      hiking: 0.35, nightlife: 0.35, partying: 0.15, 'small-groups': 0.85,
      'spectrum-pace': 0.5, 'spectrum-spend': 0.75, 'spectrum-familiarity': 0.7,
      'spectrum-comfort': 0.3,
    },
    inclusions: ['Return flights', '9 nights accommodation', 'Six game drives with a ranger', 'Three winery visits', 'Table Mountain cable car', 'All meals on safari'],
    exclusions: ['Travel insurance', 'Most meals in Cape Town', 'Gratuities for rangers'],
    images: [u('1580060839134-75a5edca2e99'), u('1516426122078-c23e76319801')],
    months: [10, 11, 12, 1, 2, 3],
  },

  // ─────────────────────────── BEACH / ALL-INCLUSIVE ───────────────────────
  {
    ref: 'PUNTA-CANA-AI-7',
    provider: 'maple-leaf-vacations',
    title: 'Punta Cana All-Inclusive: Bávaro Beach Resort',
    description:
      'Seven nights all-inclusive on Bávaro Beach. Six restaurants, four pools, unlimited drinks and a daily activity programme. Rooms are standard doubles with a partial ocean view. Straightforward, well-run and a long way from a hiking holiday.',
    destinationSlug: 'punta-cana',
    country: 'DO', region: 'La Altagracia', city: 'Punta Cana', continent: 'Caribbean',
    arrivalIata: 'PUJ',
    departures: ['YYZ', 'YUL', 'YOW', 'YHZ', 'YWG', 'YYC'],
    nights: 7,
    basePriceCents: 148_900,
    regularPriceCents: 199_900,
    gatewayPremium: { YYC: 22_000, YWG: 15_000, YHZ: 8_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals and drinks included',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Beach resort', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 1,
    tripStyle: ['all-inclusive', 'resort', 'flight-hotel'],
    attributes: {
      beaches: 1.0, relaxation: 0.95, 'all-inclusive': 1.0, resorts: 1.0,
      'resort-stays': 1.0, swimming: 0.9, spa: 0.6, wellness: 0.5,
      nightlife: 0.55, partying: 0.5, bars: 0.7, cocktails: 0.75,
      'large-groups': 0.5, 'couples-travel': 0.7, luxury: 0.55,
      hiking: 0.02, adventure: 0.1, outdoors: 0.2, nature: 0.2,
      'local-culture': 0.15, museums: 0.02, history: 0.05, 'local-cuisine': 0.25,
      'slow-travel': 0.6, 'organised-activities': 0.8,
      'spectrum-pace': 0.15, 'spectrum-comfort': 0.1, 'spectrum-spend': 0.5,
      'spectrum-immersion': 0.85, 'spectrum-guidance': 0.6, 'spectrum-familiarity': 0.25,
    },
    inclusions: ['Return flights', '7 nights all-inclusive', 'Airport transfers', 'All meals, snacks and drinks', 'Non-motorised water sports', 'Daily activity programme'],
    exclusions: ['Travel insurance', 'Spa treatments', 'Motorised water sports', 'Excursions'],
    images: [u('1544551763-46a013bb70d5'), u('1507525428034-b723cf961d3e')],
    cancellationPolicy: 'Non-refundable after 21 days. Date changes permitted for a fee.',
    months: [1, 2, 3, 4, 5, 11, 12],
  },
  {
    ref: 'RIVIERA-MAYA-AI-7',
    provider: 'maple-leaf-vacations',
    title: 'Riviera Maya All-Inclusive with Cenote Day Trip',
    description:
      'Seven nights all-inclusive south of Playa del Carmen, with one included day trip to a cenote and the Tulum ruins. Adults-only resort with five restaurants and a swim-up bar.',
    destinationSlug: 'riviera-maya',
    country: 'MX', region: 'Quintana Roo', city: 'Playa del Carmen', continent: 'North America',
    arrivalIata: 'CUN',
    departures: ['YYZ', 'YUL', 'YVR', 'YYC', 'YEG', 'YWG', 'YOW'],
    nights: 7,
    basePriceCents: 164_900,
    regularPriceCents: 214_900,
    gatewayPremium: { YVR: 12_000, YYC: 8_000, YEG: 10_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals and drinks included',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Adults-only beach resort', accommodationQuality: 4,
    minAge: 18,
    physicalDifficulty: 'EASY', activityLevel: 1,
    tripStyle: ['all-inclusive', 'resort', 'flight-hotel'],
    attributes: {
      beaches: 0.95, relaxation: 0.9, 'all-inclusive': 1.0, resorts: 0.95,
      'resort-stays': 0.95, swimming: 0.9, cocktails: 0.8, bars: 0.75,
      nightlife: 0.6, partying: 0.55, 'couples-travel': 0.85, spa: 0.65,
      archaeology: 0.4, history: 0.35, 'local-culture': 0.25,
      hiking: 0.05, adventure: 0.2, snorkelling: 0.45,
      'spectrum-pace': 0.2, 'spectrum-comfort': 0.15, 'spectrum-spend': 0.55,
      'spectrum-immersion': 0.8, 'spectrum-rhythm': 0.6,
    },
    inclusions: ['Return flights', '7 nights all-inclusive, adults only', 'Airport transfers', 'Cenote and Tulum day trip', 'All meals and drinks'],
    exclusions: ['Travel insurance', 'Spa treatments', 'Additional excursions'],
    images: [u('1518638150340-f706e86654de'), u('1512453979798-5ea266f8880c')],
    months: [1, 2, 3, 4, 11, 12],
  },
  {
    ref: 'ALGARVE-GOLF-7',
    provider: 'maple-leaf-vacations',
    title: 'Algarve: Coastal Resort & Golf',
    description:
      'Seven nights on the Algarve coast near Albufeira. Room only, so you can eat where you like. Three rounds of golf included at two nearby courses. Walking distance to the beach and the old town.',
    destinationSlug: 'algarve',
    country: 'PT', region: 'Algarve', city: 'Albufeira', continent: 'Europe',
    arrivalIata: 'LIS',
    departures: ['YYZ', 'YUL'],
    nights: 7,
    basePriceCents: 189_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: false,
    activitiesIncluded: true, transportIncluded: false, guideIncluded: false,
    accommodationType: 'Coastal resort hotel', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['flight-hotel', 'resort'],
    attributes: {
      golf: 1.0, beaches: 0.85, relaxation: 0.8, swimming: 0.7, resorts: 0.7,
      food: 0.5, wine: 0.5, 'local-cuisine': 0.5, nightlife: 0.45, bars: 0.5,
      'couples-travel': 0.6, luxury: 0.5, hiking: 0.15, adventure: 0.15,
      'spectrum-pace': 0.3, 'spectrum-spend': 0.5, 'spectrum-comfort': 0.2,
    },
    inclusions: ['Return flights to Lisbon', '7 nights room only', 'Three rounds of golf with cart', 'Car hire for the week'],
    exclusions: ['Travel insurance', 'All meals', 'Transfers', 'Golf club hire'],
    images: [u('1535131749006-b7f58c99034b')],
    months: [3, 4, 5, 6, 9, 10],
  },
  {
    ref: 'ZANZIBAR-BEACH-9',
    provider: 'still-water-retreats',
    title: 'Zanzibar: Beach & Stone Town',
    description:
      'Nine nights on the east coast of Zanzibar with two nights in Stone Town at the start. Half board at a small beachfront hotel with fourteen rooms. Days are yours — the hotel arranges snorkelling, dhow trips and a spice farm visit if you want them.',
    destinationSlug: 'zanzibar',
    country: 'TZ', region: 'Zanzibar', city: 'Stone Town', continent: 'Africa',
    arrivalIata: 'JRO',
    departures: ['YYZ', 'YUL'],
    nights: 9,
    basePriceCents: 398_900,
    regularPriceCents: 449_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Half board',
    activitiesIncluded: false, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Small beachfront hotel', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 1,
    tripStyle: ['wellness', 'resort', 'cultural'],
    attributes: {
      beaches: 0.95, relaxation: 0.9, swimming: 0.85, snorkelling: 0.7,
      wellness: 0.7, spa: 0.6, 'quiet-evenings': 0.85, 'slow-travel': 0.85,
      'local-culture': 0.6, history: 0.5, 'boutique-hotels': 0.8,
      'unique-stays': 0.6, photography: 0.6, 'couples-travel': 0.75,
      nightlife: 0.15, partying: 0.08, hiking: 0.1, adventure: 0.3,
      'spectrum-pace': 0.15, 'spectrum-familiarity': 0.75, 'spectrum-spend': 0.6,
      'spectrum-rhythm': 0.25, 'spectrum-sociability': 0.3,
    },
    inclusions: ['Return flights', '2 nights Stone Town, 7 nights beachfront', 'Half board on the coast', 'All transfers'],
    exclusions: ['Travel insurance', 'Excursions', 'Lunches', 'Drinks'],
    images: [u('1516026672322-bc52d61a55d5'), u('1505881502353-a1986add3762')],
    months: [6, 7, 8, 9, 12, 1, 2],
  },

  // ─────────────────────────── CITY & CULTURE ──────────────────────────────
  {
    ref: 'JAPAN-CULTURE-12',
    provider: 'cedar-rail-journeys',
    title: 'Japan by Rail: Tokyo, Kanazawa & Kyoto',
    description:
      'Twelve nights travelling by rail from Tokyo through Kanazawa to Kyoto, with two nights in a traditional ryokan. A rail pass is included and several days are deliberately unstructured. Expect a lot of walking in cities, but nothing strenuous.',
    destinationSlug: 'japan',
    country: 'JP', region: 'Honshu', city: 'Tokyo', continent: 'Asia',
    arrivalIata: 'NRT',
    departures: ['YVR', 'YYZ', 'YYC', 'YUL'],
    nights: 12,
    basePriceCents: 512_900,
    regularPriceCents: 589_900,
    gatewayPremium: { YYZ: 18_000, YUL: 24_000, YYC: 6_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '12 breakfasts, 2 ryokan dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'City hotels and a traditional ryokan', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 3,
    tripStyle: ['cultural', 'city-break', 'tour'],
    soloFriendly: true,
    attributes: {
      'local-culture': 0.95, cities: 0.95, history: 0.85, architecture: 0.85,
      food: 0.9, 'local-cuisine': 0.95, 'street-food': 0.75, museums: 0.7,
      'religion-spirituality': 0.7, art: 0.65, photography: 0.8,
      'independent-travel': 0.8, 'slow-travel': 0.5, 'unique-stays': 0.8,
      'language-immersion': 0.5, nightlife: 0.55, bars: 0.55, partying: 0.25,
      'comfortable-transport': 0.85, hiking: 0.2, beaches: 0.05, adventure: 0.35,
      'spectrum-familiarity': 0.85, 'spectrum-pace': 0.6, 'spectrum-guidance': 0.25,
      'spectrum-immersion': 0.3, 'spectrum-spend': 0.6,
    },
    inclusions: ['Return flights', '12 nights accommodation including 2 in a ryokan', '7-day Japan Rail Pass', 'Airport transfers', 'Tokyo and Kyoto orientation walks', '12 breakfasts and 2 ryokan dinners'],
    exclusions: ['Travel insurance', 'Most meals', 'Temple entry fees', 'Optional guided days'],
    images: [u('1493976040374-85c8e12f0c0e'), u('1545569341-9eb8b30979d9'), u('1528360983277-13d401cdc186')],
    months: [3, 4, 5, 10, 11],
  },
  {
    ref: 'LISBON-CITY-4',
    provider: 'gate-seven-city-breaks',
    title: 'Lisbon City Break: Four Nights in Chiado',
    description:
      'Four nights in a four-star hotel in Chiago, walking distance to Baixa, Bairro Alto and the tram lines. Flight and hotel only — the rest of the trip is yours to build.',
    destinationSlug: 'lisbon',
    country: 'PT', city: 'Lisbon', continent: 'Europe',
    arrivalIata: 'LIS',
    departures: ['YYZ', 'YUL', 'YHZ'],
    nights: 4,
    basePriceCents: 112_900,
    regularPriceCents: 139_900,
    gatewayPremium: { YHZ: -18_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast daily',
    activitiesIncluded: false, transportIncluded: false, guideIncluded: false,
    accommodationType: '4-star city hotel', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['city-break', 'flight-hotel'],
    soloFriendly: true,
    attributes: {
      cities: 0.95, 'local-culture': 0.8, food: 0.8, 'local-cuisine': 0.8,
      wine: 0.7, 'coffee-culture': 0.75, architecture: 0.8, history: 0.7,
      museums: 0.6, nightlife: 0.7, bars: 0.7, music: 0.6,
      'independent-travel': 0.9, 'boutique-hotels': 0.5,
      hiking: 0.05, outdoors: 0.15, beaches: 0.3, adventure: 0.15,
      'spectrum-pace': 0.5, 'spectrum-guidance': 0.1, 'spectrum-planning': 0.7,
      'spectrum-spend': 0.45, 'spectrum-rhythm': 0.65,
    },
    inclusions: ['Return flights', '4 nights in a 4-star hotel', 'Daily breakfast'],
    exclusions: ['Travel insurance', 'Transfers', 'All meals except breakfast', 'Activities'],
    images: [u('1585208798174-6cedd86e019a'), u('1513735492246-483525079686')],
    months: [2, 3, 4, 5, 6, 9, 10, 11],
  },
  {
    ref: 'ROME-CITY-5',
    provider: 'gate-seven-city-breaks',
    title: 'Rome: Five Nights near the Pantheon',
    description:
      'Five nights in the historic centre with skip-the-line entry to the Colosseum and the Vatican Museums included. Everything else is walking distance.',
    destinationSlug: 'rome',
    country: 'IT', city: 'Rome', continent: 'Europe',
    arrivalIata: 'FCO',
    departures: ['YYZ', 'YUL'],
    nights: 5,
    basePriceCents: 158_900,
    regularPriceCents: 189_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast daily',
    activitiesIncluded: true, transportIncluded: false, guideIncluded: false,
    accommodationType: '4-star hotel', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 3,
    tripStyle: ['city-break', 'cultural', 'flight-hotel'],
    attributes: {
      history: 0.98, archaeology: 0.9, architecture: 0.9, museums: 0.85, art: 0.85,
      cities: 0.9, 'unesco-sites': 0.85, food: 0.8, 'local-cuisine': 0.8,
      'religion-spirituality': 0.6, 'coffee-culture': 0.7, wine: 0.6,
      nightlife: 0.45, 'independent-travel': 0.7, hiking: 0.05, beaches: 0.02,
      'spectrum-pace': 0.6, 'spectrum-immersion': 0.6, 'spectrum-spend': 0.5,
    },
    inclusions: ['Return flights', '5 nights in the historic centre', 'Daily breakfast', 'Colosseum skip-the-line entry', 'Vatican Museums entry'],
    exclusions: ['Travel insurance', 'Transfers', 'Most meals'],
    images: [u('1552832230-c0197dd311b5'), u('1515542622106-78bda8ba0e5b')],
    months: [3, 4, 5, 9, 10, 11],
  },
  {
    ref: 'ICELAND-RING-8',
    provider: 'trailhead-domestic',
    title: 'Iceland: Self-Drive Ring Road',
    description:
      'Eight nights driving the Ring Road with accommodation booked ahead of you at each stop. Car hire and a detailed route guide included. You drive and choose your own stops, which suits people who dislike being on a coach.',
    destinationSlug: 'iceland',
    country: 'IS', city: 'Reykjavík', continent: 'Europe',
    arrivalIata: 'KEF',
    departures: ['YYZ', 'YHZ', 'YUL'],
    nights: 8,
    basePriceCents: 289_900,
    regularPriceCents: 339_900,
    gatewayPremium: { YHZ: -22_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast daily',
    activitiesIncluded: false, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Guesthouses and small hotels', accommodationQuality: 3,
    physicalDifficulty: 'MODERATE', activityLevel: 3,
    tripStyle: ['road-trip', 'adventure-tour'],
    soloFriendly: true,
    attributes: {
      'road-trips': 1.0, nature: 0.95, outdoors: 0.9, photography: 0.9,
      adventure: 0.7, hiking: 0.6, 'independent-travel': 0.95, wildlife: 0.5,
      mountains: 0.65, 'unique-stays': 0.5, 'quiet-evenings': 0.7,
      'spontaneous-travel': 0.6, luxury: 0.35, nightlife: 0.15, partying: 0.05,
      beaches: 0.1, 'local-culture': 0.45, wellness: 0.5, spa: 0.55,
      'spectrum-planning': 0.6, 'spectrum-guidance': 0.05, 'spectrum-comfort': 0.6,
      'spectrum-pace': 0.6, 'spectrum-spend': 0.45,
    },
    inclusions: ['Return flights to Keflavík', '8 nights in guesthouses along the route', 'Compact 4x4 car hire with insurance', 'Detailed route guide', 'Daily breakfast'],
    exclusions: ['Travel insurance', 'Fuel', 'Meals other than breakfast', 'Blue Lagoon entry'],
    images: [u('1504829857797-ddff29c27927'), u('1520769945061-0a448c463865')],
    months: [5, 6, 7, 8, 9],
  },
  {
    ref: 'PERU-INCA-11',
    provider: 'northbound-adventures',
    title: 'Peru: Sacred Valley & the Inca Trail',
    description:
      'Eleven nights in Peru including the four-day Inca Trail to Machu Picchu. Permits are included but limited, so departures sell out months ahead. Altitude is a real factor — two acclimatisation days in Cusco are built in.',
    destinationSlug: 'cusco',
    country: 'PE', region: 'Cusco', city: 'Cusco', continent: 'South America',
    arrivalIata: 'LIM',
    departures: ['YYZ', 'YUL', 'YVR'],
    nights: 11,
    basePriceCents: 442_900,
    regularPriceCents: 498_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals on the trail, breakfasts elsewhere',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Hotels and trail camping', accommodationQuality: 3,
    groupSizeMax: 14, minAge: 18,
    physicalDifficulty: 'CHALLENGING', activityLevel: 5,
    tripStyle: ['hiking-tour', 'adventure-tour', 'cultural'],
    soloFriendly: true,
    attributes: {
      hiking: 0.95, adventure: 0.9, archaeology: 0.95, history: 0.9, mountains: 0.85,
      camping: 0.7, outdoors: 0.9, 'local-culture': 0.8, 'indigenous-culture': 0.8,
      photography: 0.8, 'unesco-sites': 0.9, 'small-groups': 0.85, food: 0.6,
      'meeting-new-people': 0.7, luxury: 0.2, nightlife: 0.2, beaches: 0.02,
      'spectrum-pace': 0.8, 'spectrum-comfort': 0.85, 'spectrum-familiarity': 0.8,
      'spectrum-guidance': 0.8, 'spectrum-spend': 0.45,
    },
    inclusions: ['Return flights', 'Internal flights Lima to Cusco', '11 nights accommodation', 'Inca Trail permit and porters', 'All meals on the trail', 'Machu Picchu entry', 'English-speaking guide'],
    exclusions: ['Travel insurance (mandatory)', 'Meals in Cusco and Lima', 'Sleeping bag hire', 'Gratuities for porters'],
    images: [u('1526392060635-9d6019884377'), u('1587595431973-160d0d94add1')],
    months: [4, 5, 6, 7, 8, 9, 10],
  },

  // ────────────────────────────── SKI ──────────────────────────────────────
  {
    ref: 'ALPS-SKI-7',
    provider: 'summit-line-ski',
    title: 'French Alps: Ski Week in the Three Valleys',
    description:
      'Seven nights in a catered chalet in Méribel with a six-day Three Valleys lift pass included. Breakfast, afternoon tea and six dinners with wine. Ski hire and lessons are extra.',
    destinationSlug: 'french-alps',
    country: 'FR', region: 'Savoie', city: 'Méribel', continent: 'Europe',
    arrivalIata: 'GVA',
    departures: ['YYZ', 'YUL'],
    nights: 7,
    basePriceCents: 328_900,
    regularPriceCents: 379_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast, afternoon tea and 6 dinners with wine',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Catered chalet', accommodationQuality: 4,
    groupSizeMax: 16,
    physicalDifficulty: 'MODERATE', activityLevel: 4,
    tripStyle: ['ski', 'flight-hotel'],
    soloFriendly: true,
    attributes: {
      skiing: 1.0, snowboarding: 0.85, mountains: 0.95, outdoors: 0.8,
      'meeting-new-people': 0.6, 'small-groups': 0.7, bars: 0.65, nightlife: 0.6,
      food: 0.7, wine: 0.65, 'comfortable-transport': 0.6, spa: 0.4,
      luxury: 0.6, adventure: 0.6, hiking: 0.25, beaches: 0.0, swimming: 0.1,
      'spectrum-pace': 0.7, 'spectrum-spend': 0.6, 'spectrum-rhythm': 0.6,
      'spectrum-sociability': 0.65,
    },
    inclusions: ['Return flights to Geneva', 'Resort transfers', '7 nights catered chalet', '6-day Three Valleys lift pass', 'Breakfast, afternoon tea and 6 dinners with wine'],
    exclusions: ['Travel insurance', 'Ski and boot hire', 'Lessons', 'Lunches on the mountain'],
    images: [u('1551524164-687a55dd1126'), u('1605540436563-5bca919ae766')],
    months: [1, 2, 3, 12],
  },
  {
    ref: 'JAPOW-SKI-9',
    provider: 'summit-line-ski',
    title: 'Japan: Niseko Powder Week',
    description:
      'Nine nights in Niseko with a seven-day all-mountain pass. Accommodation is a ski-in ski-out hotel with an onsen. Famous for consistent, deep powder and long queues at the good restaurants.',
    destinationSlug: 'japan',
    country: 'JP', region: 'Hokkaido', city: 'Niseko', continent: 'Asia',
    arrivalIata: 'NRT',
    departures: ['YVR', 'YYC', 'YYZ'],
    nights: 9,
    basePriceCents: 498_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast daily',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Ski-in ski-out hotel with onsen', accommodationQuality: 4,
    physicalDifficulty: 'CHALLENGING', activityLevel: 5,
    tripStyle: ['ski', 'flight-hotel'],
    attributes: {
      skiing: 1.0, snowboarding: 0.95, mountains: 0.9, adventure: 0.75,
      wellness: 0.6, spa: 0.7, food: 0.8, 'local-cuisine': 0.8,
      'local-culture': 0.6, bars: 0.6, nightlife: 0.55, luxury: 0.65,
      'unique-stays': 0.6, hiking: 0.1, beaches: 0.0,
      'spectrum-familiarity': 0.85, 'spectrum-pace': 0.75, 'spectrum-spend': 0.65,
    },
    inclusions: ['Return flights', 'Transfers from Sapporo', '9 nights ski-in ski-out', '7-day all-mountain pass', 'Daily breakfast', 'Onsen access'],
    exclusions: ['Travel insurance', 'Ski hire', 'Most meals', 'Lessons'],
    images: [u('1551698618-1dfe5d97d256')],
    months: [1, 2, 12],
  },

  // ─────────────────────── SOCIAL / SOLO-FRIENDLY ──────────────────────────
  {
    ref: 'THAILAND-SOCIAL-14',
    provider: 'wander-collective',
    title: 'Thailand: Bangkok, Chiang Mai & the Islands',
    description:
      'Fourteen nights for solo travellers in their twenties and thirties, moving from Bangkok north to Chiang Mai and then south to Koh Tao and Koh Phangan. Shared twin rooms with another traveller of the same group by default, or pay a supplement for a private room. Nights out are part of the trip.',
    destinationSlug: 'thailand',
    country: 'TH', city: 'Bangkok', continent: 'Asia',
    arrivalIata: 'BKK',
    departures: ['YVR', 'YYZ', 'YUL'],
    nights: 14,
    basePriceCents: 348_900,
    regularPriceCents: 419_900,
    gatewayPremium: { YYZ: 14_000, YUL: 18_000 },
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '14 breakfasts, 4 group dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Hostels and small hotels', accommodationQuality: 2,
    groupSizeMin: 8, groupSizeMax: 18, minAge: 18,
    physicalDifficulty: 'MODERATE', activityLevel: 3,
    tripStyle: ['group-travel', 'solo-friendly', 'adventure-tour'],
    soloFriendly: true,
    attributes: {
      'meeting-new-people': 1.0, 'social-hostels': 0.9, hostels: 0.9,
      'large-groups': 0.7, 'small-groups': 0.6, partying: 0.85, nightlife: 0.9,
      bars: 0.85, clubs: 0.7, 'street-food': 0.9, food: 0.85, 'night-markets': 0.85,
      beaches: 0.85, swimming: 0.8, 'scuba-diving': 0.6, snorkelling: 0.65,
      'budget-travel': 0.85, 'local-culture': 0.7, adventure: 0.7, cities: 0.7,
      'solo-travel': 0.9, luxury: 0.1, 'luxury-hotels': 0.05, 'fine-dining': 0.15,
      'quiet-evenings': 0.15, hiking: 0.35, 'religion-spirituality': 0.5,
      'spectrum-sociability': 0.95, 'spectrum-rhythm': 0.85, 'spectrum-spend': 0.2,
      'spectrum-comfort': 0.7, 'spectrum-familiarity': 0.8, 'spectrum-pace': 0.7,
    },
    inclusions: ['Return flights', 'All internal transport including two domestic flights', '14 nights shared accommodation', 'Trip leader throughout', '14 breakfasts and 4 group dinners', 'Island boat transfers'],
    exclusions: ['Travel insurance', 'Private room supplement', 'Most meals', 'Diving certification'],
    images: [u('1528181304800-259b08848526'), u('1552465011-b4e21bf6e79a'), u('1506665531195-3566af2b4dfa')],
    cancellationPolicy: 'Free cancellation up to 45 days. 50% refund 21-44 days.',
    months: [1, 2, 3, 11, 12],
  },
  {
    ref: 'BALI-WELLNESS-10',
    provider: 'still-water-retreats',
    title: 'Bali: Ubud Yoga & Coastal Retreat',
    description:
      'Ten nights split between Ubud and the Bukit Peninsula. Twice-daily yoga, two spa treatments and a plant-based meal plan included. Quiet, structured and not a party destination — evenings finish early.',
    destinationSlug: 'bali',
    country: 'ID', region: 'Bali', city: 'Ubud', continent: 'Asia',
    arrivalIata: 'DPS',
    departures: ['YVR', 'YYZ'],
    nights: 10,
    basePriceCents: 372_900,
    regularPriceCents: 429_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast and dinner daily',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: false,
    accommodationType: 'Retreat villas', accommodationQuality: 4,
    groupSizeMax: 16, minAge: 18,
    physicalDifficulty: 'EASY', activityLevel: 3,
    tripStyle: ['wellness', 'resort'],
    soloFriendly: true,
    attributes: {
      yoga: 1.0, wellness: 1.0, spa: 0.9, relaxation: 0.9, 'quiet-evenings': 0.9,
      'slow-travel': 0.85, nature: 0.75, beaches: 0.7, swimming: 0.7,
      'local-culture': 0.6, 'religion-spirituality': 0.6, food: 0.6,
      'meeting-new-people': 0.6, 'small-groups': 0.8, fitness: 0.6,
      surfing: 0.3, nightlife: 0.05, partying: 0.02, bars: 0.05, clubs: 0.02,
      'fine-dining': 0.3, luxury: 0.6, hiking: 0.35, adventure: 0.25,
      'spectrum-pace': 0.25, 'spectrum-rhythm': 0.1, 'spectrum-sociability': 0.45,
      'spectrum-spend': 0.55, 'spectrum-guidance': 0.75,
    },
    inclusions: ['Return flights', '10 nights in retreat villas', 'Twice-daily yoga', 'Two spa treatments', 'Breakfast and dinner daily', 'All transfers'],
    exclusions: ['Travel insurance', 'Lunches', 'Additional treatments', 'Surf lessons'],
    images: [u('1537996194471-e657df975ab4'), u('1544161515-4ab6ce6db874')],
    months: [4, 5, 6, 7, 8, 9],
  },
  {
    ref: 'GREECE-SAIL-8',
    provider: 'wander-collective',
    title: 'Greece: Cyclades Sailing Week',
    description:
      'Eight nights sailing between Mykonos, Paros, Naxos and Ios on a shared yacht with a skipper. Eight to ten people per boat in twin cabins. Swim stops daily, dinner ashore most nights, and a reputation for late ones.',
    destinationSlug: 'cyclades',
    country: 'GR', region: 'South Aegean', continent: 'Europe',
    arrivalIata: 'ATH',
    departures: ['YYZ', 'YUL'],
    nights: 8,
    basePriceCents: 268_900,
    regularPriceCents: 309_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfasts and some lunches on board',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Shared yacht, twin cabins', accommodationQuality: 3,
    groupSizeMin: 6, groupSizeMax: 10, minAge: 18,
    physicalDifficulty: 'EASY', activityLevel: 3,
    tripStyle: ['group-travel', 'solo-friendly', 'adventure-tour'],
    soloFriendly: true,
    attributes: {
      sailing: 1.0, swimming: 0.9, beaches: 0.9, 'water-sports': 0.7,
      'meeting-new-people': 0.9, 'small-groups': 0.95, partying: 0.7,
      nightlife: 0.75, bars: 0.75, cocktails: 0.6, 'solo-travel': 0.8,
      food: 0.7, 'local-cuisine': 0.7, adventure: 0.6, outdoors: 0.7,
      'unique-stays': 0.8, relaxation: 0.6, history: 0.35,
      luxury: 0.35, 'luxury-hotels': 0.1, hiking: 0.15, 'private-rooms': 0.15,
      'spectrum-sociability': 0.9, 'spectrum-rhythm': 0.75, 'spectrum-comfort': 0.55,
      'spectrum-spend': 0.45, 'spectrum-planning': 0.55,
    },
    inclusions: ['Return flights to Athens', '8 nights on board in a twin cabin', 'Skipper', 'Fuel and mooring fees', 'Breakfasts and some lunches'],
    exclusions: ['Travel insurance', 'Dinners ashore', 'Cabin supplement for sole occupancy'],
    images: [u('1533105079780-92b9be482077'), u('1519046904884-53103b34b206')],
    months: [5, 6, 7, 8, 9],
  },

  // ──────────────────────────── CRUISE ─────────────────────────────────────
  {
    ref: 'ATLANTIC-CANADA-CRUISE-7',
    provider: 'harbour-crossing-cruises',
    title: 'Atlantic Canada: Small-Ship Coastal Voyage',
    description:
      'Seven nights on a 96-passenger expedition ship from Halifax around Cape Breton and into Newfoundland. Zodiac landings, a naturalist on board and no formal nights. Sea conditions can be rough in the Cabot Strait.',
    destinationSlug: 'newfoundland',
    country: 'CA', region: 'Atlantic Canada', city: 'Halifax', continent: 'North America',
    arrivalIata: 'YHZ',
    departures: ['YHZ', 'YYZ', 'YUL'],
    nights: 7,
    basePriceCents: 469_900,
    regularPriceCents: 529_900,
    gatewayPremium: { YYZ: 32_000, YUL: 28_000 },
    airfareIncluded: false, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals on board',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Expedition ship cabins', accommodationQuality: 4,
    groupSizeMax: 96,
    physicalDifficulty: 'MODERATE', activityLevel: 3,
    tripStyle: ['cruise', 'expedition'],
    attributes: {
      cruises: 1.0, wildlife: 0.85, nature: 0.85, outdoors: 0.8, photography: 0.8,
      'local-culture': 0.7, history: 0.6, sailing: 0.6, adventure: 0.6,
      hiking: 0.45, 'quiet-evenings': 0.7, food: 0.65, luxury: 0.6,
      'organised-activities': 0.85, 'guided-tours': 0.8, 'large-groups': 0.6,
      nightlife: 0.15, partying: 0.08, beaches: 0.2,
      'spectrum-guidance': 0.9, 'spectrum-pace': 0.5, 'spectrum-familiarity': 0.2,
      'spectrum-spend': 0.65, 'spectrum-comfort': 0.45,
    },
    inclusions: ['7 nights on board', 'All meals', 'Zodiac excursions', 'Naturalist and historian on board', 'Port fees'],
    exclusions: ['Flights to Halifax', 'Travel insurance', 'Alcoholic drinks', 'Gratuities'],
    images: [u('1580541631971-a0e7f6b2b27f'), u('1559827260-dc66d52bef19')],
    months: [6, 7, 8, 9],
  },

  // ───────────────────── DELIBERATELY INCOMPLETE RECORDS ───────────────────
  {
    ref: 'FLASH-BCN-3',
    provider: 'atlas-flash',
    title: 'Barcelona Flash Sale — 3 Nights',
    description: 'Three nights in Barcelona. Limited availability.',
    destinationSlug: 'barcelona',
    country: 'ES', city: 'Barcelona', continent: 'Europe',
    arrivalIata: 'BCN',
    departures: ['YYZ'],
    nights: 3,
    basePriceCents: 89_900,
    regularPriceCents: 149_900,
    // The provider does not state these. We show "Not specified" rather than guessing.
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: null,
    activitiesIncluded: null, transportIncluded: null, guideIncluded: null,
    accommodationType: null, accommodationQuality: null,
    physicalDifficulty: 'NOT_SPECIFIED',
    tripStyle: ['city-break'],
    incomplete: true,
    attributes: { cities: 0.85, architecture: 0.7, nightlife: 0.6, beaches: 0.4, food: 0.6 },
    inclusions: ['Return flights', '3 nights accommodation'],
    exclusions: [],
    images: [u('1539037116277-4db20889f2d4')],
    months: [3, 4, 5, 9, 10],
  },
  {
    ref: 'FLASH-CUN-5',
    provider: 'atlas-flash',
    title: 'Cancún 5 Nights — Last Minute',
    description: 'Five nights in Cancún, departing soon.',
    destinationSlug: 'mexico',
    country: 'MX', city: 'Cancún', continent: 'North America',
    arrivalIata: 'CUN',
    departures: ['YYZ', 'YUL'],
    nights: 5,
    basePriceCents: 99_900,
    regularPriceCents: 159_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: null,
    activitiesIncluded: null, transportIncluded: null, guideIncluded: null,
    accommodationType: null, accommodationQuality: null,
    physicalDifficulty: 'NOT_SPECIFIED',
    tripStyle: ['flight-hotel'],
    incomplete: true,
    attributes: { beaches: 0.85, relaxation: 0.7, swimming: 0.7, nightlife: 0.5 },
    inclusions: ['Return flights', '5 nights accommodation'],
    exclusions: [],
    images: [u('1512453979798-5ea266f8880c')],
    months: [1, 2, 3, 4, 10, 11, 12],
  },
  {
    ref: 'OAXACA-FOOD-6',
    provider: 'terra-vine-collective',
    title: 'Oaxaca: Markets, Mezcal & Mole',
    description:
      'Six nights in Oaxaca City with day trips to Teotitlán del Valle and a mezcal palenque in the valleys. Two cooking classes focused on the seven moles, and a market tour with a local chef.',
    destinationSlug: 'oaxaca',
    country: 'MX', region: 'Oaxaca', city: 'Oaxaca', continent: 'North America',
    arrivalIata: 'CUN',
    departures: ['YYZ', 'YVR'],
    nights: 6,
    basePriceCents: 228_900,
    regularPriceCents: 264_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '6 breakfasts, 3 dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Boutique hotel in a colonial building', accommodationQuality: 4,
    groupSizeMax: 12,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['food-wine', 'cultural', 'tour'],
    attributes: {
      food: 1.0, 'local-cuisine': 0.95, 'cooking-classes': 0.9, 'street-food': 0.8,
      'food-tours': 0.9, cocktails: 0.7, 'local-culture': 0.9, art: 0.8,
      history: 0.7, architecture: 0.7, 'indigenous-culture': 0.85,
      'boutique-hotels': 0.8, 'small-groups': 0.85, 'night-markets': 0.7,
      festivals: 0.5, luxury: 0.5, hiking: 0.15, beaches: 0.02, partying: 0.25,
      'spectrum-immersion': 0.2, 'spectrum-pace': 0.45, 'spectrum-spend': 0.5,
      'spectrum-familiarity': 0.65,
    },
    inclusions: ['Return flights', '6 nights boutique hotel', 'Two cooking classes', 'Market tour with a chef', 'Mezcal palenque visit', '6 breakfasts and 3 dinners'],
    exclusions: ['Travel insurance', 'Lunches', 'Additional mezcal purchases'],
    images: [u('1518638150340-f706e86654de')],
    months: [1, 2, 3, 10, 11],
  },
  {
    ref: 'SERENGETI-SAFARI-9',
    provider: 'meridian-safari-co',
    title: 'Tanzania: Serengeti & Ngorongoro Safari',
    description:
      'Nine nights on safari through the Serengeti and the Ngorongoro Crater, staying in permanent tented camps. Two game drives daily in a shared 4x4 with a maximum of six guests. Timed for the migration river crossings where possible, though wildlife movement is never guaranteed.',
    destinationSlug: 'serengeti',
    country: 'TZ', region: 'Northern Circuit', city: 'Arusha', continent: 'Africa',
    arrivalIata: 'JRO',
    departures: ['YYZ', 'YUL'],
    nights: 9,
    basePriceCents: 712_900,
    regularPriceCents: 789_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'All meals',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Permanent tented camps', accommodationQuality: 4,
    groupSizeMax: 6, minAge: 12,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['adventure-tour', 'expedition', 'tour'],
    attributes: {
      wildlife: 1.0, photography: 0.95, nature: 0.95, outdoors: 0.85,
      'guided-tours': 0.95, 'small-groups': 0.95, glamping: 0.85,
      'unique-stays': 0.8, adventure: 0.7, 'quiet-evenings': 0.8,
      luxury: 0.65, camping: 0.5, 'local-culture': 0.55, 'indigenous-culture': 0.6,
      hiking: 0.2, beaches: 0.02, nightlife: 0.02, partying: 0.02, cities: 0.05,
      'spectrum-familiarity': 0.9, 'spectrum-guidance': 0.95, 'spectrum-pace': 0.5,
      'spectrum-spend': 0.8, 'spectrum-rhythm': 0.1,
    },
    inclusions: ['Return flights', '9 nights in tented camps', 'All meals', 'Two game drives daily', 'Park and crater fees', 'Professional safari guide'],
    exclusions: ['Travel insurance', 'Tanzania visa', 'Drinks', 'Gratuities', 'Balloon safari'],
    images: [u('1516426122078-c23e76319801'), u('1534177616072-ef7dc120449d')],
    months: [6, 7, 8, 9, 1, 2],
  },
  {
    ref: 'QUEBEC-WINTER-4',
    provider: 'trailhead-domestic',
    title: 'Québec City: Winter Carnival Weekend',
    description:
      'Four nights inside the old walls during Carnaval. Includes an effigy pass, a dog-sledding afternoon and a night at the ice hotel bar. Cold, and that is the point.',
    destinationSlug: 'quebec-city',
    country: 'CA', region: 'Québec', city: 'Québec City', continent: 'North America',
    arrivalIata: 'YQB',
    departures: ['YYZ', 'YUL', 'YOW', 'YHZ'],
    nights: 4,
    basePriceCents: 98_900,
    regularPriceCents: 124_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: 'Breakfast daily',
    activitiesIncluded: true, transportIncluded: false, guideIncluded: false,
    accommodationType: 'Historic hotel in Vieux-Québec', accommodationQuality: 4,
    physicalDifficulty: 'EASY', activityLevel: 2,
    tripStyle: ['city-break', 'cultural'],
    attributes: {
      festivals: 0.95, 'local-culture': 0.85, history: 0.8, cities: 0.8,
      architecture: 0.75, food: 0.7, 'local-cuisine': 0.7, bars: 0.6,
      'unique-stays': 0.5, outdoors: 0.5, photography: 0.6, 'music': 0.5,
      nightlife: 0.55, adventure: 0.35, beaches: 0.0, hiking: 0.1,
      'spectrum-familiarity': 0.15, 'spectrum-pace': 0.6, 'spectrum-spend': 0.45,
    },
    inclusions: ['Return flights', '4 nights in Vieux-Québec', 'Daily breakfast', 'Carnaval effigy pass', 'Dog-sledding afternoon'],
    exclusions: ['Travel insurance', 'Transfers', 'Most meals', 'Winter clothing hire'],
    images: [u('1519178614-68673b201f36')],
    months: [1, 2],
  },
  {
    ref: 'ANDALUSIA-CULTURE-9',
    provider: 'cedar-rail-journeys',
    title: 'Andalusia by Rail: Seville, Córdoba & Granada',
    description:
      'Nine nights travelling by high-speed rail between the three great Moorish cities, with timed entry to the Alhambra and the Mezquita included. Two flamenco evenings and a great deal of walking on uneven streets.',
    destinationSlug: 'andalusia',
    country: 'ES', region: 'Andalusia', city: 'Seville', continent: 'Europe',
    arrivalIata: 'BCN',
    departures: ['YYZ', 'YUL'],
    nights: 9,
    basePriceCents: 334_900,
    regularPriceCents: 389_900,
    airfareIncluded: true, accommodationIncluded: true, mealsIncluded: true,
    mealsDescription: '9 breakfasts, 3 dinners',
    activitiesIncluded: true, transportIncluded: true, guideIncluded: true,
    accommodationType: 'Boutique hotels in historic centres', accommodationQuality: 4,
    groupSizeMax: 16,
    physicalDifficulty: 'MODERATE', activityLevel: 3,
    tripStyle: ['cultural', 'city-break', 'tour'],
    attributes: {
      history: 0.95, architecture: 0.95, 'unesco-sites': 0.9, 'local-culture': 0.85,
      art: 0.75, museums: 0.7, music: 0.8, 'live-entertainment': 0.8,
      food: 0.8, 'local-cuisine': 0.8, wine: 0.65, cities: 0.85,
      'religion-spirituality': 0.6, 'boutique-hotels': 0.75, 'guided-tours': 0.7,
      nightlife: 0.5, beaches: 0.15, hiking: 0.1, adventure: 0.2,
      'spectrum-pace': 0.6, 'spectrum-immersion': 0.4, 'spectrum-spend': 0.55,
      'spectrum-rhythm': 0.7,
    },
    inclusions: ['Return flights', 'All high-speed rail between cities', '9 nights in boutique hotels', 'Alhambra timed entry', 'Mezquita entry', 'Two flamenco evenings', '9 breakfasts and 3 dinners'],
    exclusions: ['Travel insurance', 'Lunches', 'Optional day trips'],
    images: [u('1539037116277-4db20889f2d4'), u('1558642452-9d2a7deb7f62')],
    months: [3, 4, 5, 9, 10, 11],
  },
]
